apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-express-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - name: express
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
